# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1378734202);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1378735564);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1378799122);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 491520);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://host01.example.com:7001/console");
user_pref("browser.startup.homepage_override.buildID", "20130108192553");
user_pref("browser.startup.homepage_override.mstone", "rv:10.0.12");
user_pref("browser.syncPromoViewsLeft", 0);
user_pref("extensions.blocklist.pingCountTotal", 42);
user_pref("extensions.blocklist.pingCountVersion", 42);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:10.0.12");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1358919776000}}}]");
user_pref("extensions.lastAppVersion", "10.0.12");
user_pref("extensions.lastPlatformVersion", "10.0.12");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 2);
user_pref("gfx.blacklist.suggested-driver-version", "<Anything with EXT_texture_from_pixmap support>");
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.msaa", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("idle.lastDailyNotification", 1378734513);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 8001);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.type", 4);
user_pref("places.database.lastMaintenance", 1378734513);
user_pref("places.history.expiration.transient_current_max_pages", 76383);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1377961982);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1381396676);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
