DROP SEQUENCE SEQ_CATALOG;

DROP TABLE CATALOG;

CREATE TABLE CATALOG (
    SKU NUMBER(10) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(50) NOT NULL,
    PRICE NUMBER(7,2) NOT NULL,
    PRIMARY KEY (SKU));

CREATE SEQUENCE SEQ_CATALOG
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOORDER;

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Black pens','Box of 12 pens (black)',4.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Blue pens','Box of 12 pens (blue)',4.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Red pens','Box of 12 pens (red)',4.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Pencils','Box of 12 #2 pencils',1.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Mechanical pencils','Box of 12 plastic mechanical pencils',3.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Small binder clips','Box of 12 binder clips (small)',1.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Large binder clips','Box of 12 binder clips (large)',3.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Rubber bands','Package of assorted rubber bands',4.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Tape','Package of 3 - clear tape in plastic dispensers',3.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Staples','Box of 1000 staples',2.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Stapler','Desk stapler (black)',6.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Paper','Package of 500 sheets multipurpose paper',6.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Legal pads','Package of 5 legal pads',7.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'File folders','100 file folders',8.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Index cards','100 3x5 index cards',2.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Sticky Notes','100 sticky notes',4.99);

INSERT INTO CATALOG (SKU, NAME, DESCRIPTION, PRICE)
VALUES (SEQ_CATALOG.NEXTVAL,'Notebook','1-subject spiral notebook',1.99);
        
COMMIT;